#!/usr/bin/env python3
"""Encode source PNGs as bounded, little-endian RGBA textures. No runtime PNG dependency."""
# SPDX-License-Identifier: GPL-3.0-or-later
from pathlib import Path
from PIL import Image
import struct
root=Path(__file__).resolve().parents[1]
for name in ('leaders','congress'):
    with Image.open(root/'art'/f'{name}.png') as src:
        im=src.convert('RGBA')
        if max(im.size)>4096: raise SystemExit('Texture exceeds 4096 pixels')
        (root/'assets'/f'{name}.cdea').write_bytes(struct.pack('<III',0x41454443,*im.size)+im.tobytes())
        print(name,im.size)
from PIL import ImageDraw,ImageFont
font=ImageFont.truetype(str(root/'art/font/Bangers-Regular.ttf'),64)
atlas=Image.new('RGBA',(1024,384));draw=ImageDraw.Draw(atlas)
adv=[]
for i in range(96):
    ch=chr(i+32);x=(i%16)*64;y=(i//16)*64
    glyph=Image.new('RGBA',(64,64))
    ImageDraw.Draw(glyph).text((2,-12),ch,font=font,fill=(255,255,255,255))
    atlas.paste(glyph,(x,y))
    adv.append(round(font.getlength(ch))+3)
(root/'assets/font.cdea').write_bytes(struct.pack('<III',0x41454443,*atlas.size)+atlas.tobytes())
(root/'src/font_metrics.hpp').write_text('// Bangers glyph advances. Generated by tools/prepare-art.py.\n#pragma once\nnamespace crisis { inline constexpr unsigned fontAdvance[96]={'+','.join(map(str,adv))+'}; }\n')
